Coordinator -> ConnectionManager: Inits
Client -> TCP Socket: Connection/Stream
ConnectionManager -> TCP Socket
ConnectionManager -> FrameController: ConnectionStream
FrameController -> ConnectionManager: Frame
FrameController -> FrameQueue: Enqueue Frame

TCP Socket --> Client: StreamingResponse
Main Process -> Coordinator: Inits


Command Parser -> Command: Frame
Command Parser -> Coordinator: Command

Command -> Command Parser
Queue --> Executor: notifies with Command
Executor --> In Memory Data Structure: Access
Executor --> Coordinator: return result

Coordinator -> FrameQueue: Dequeue
Coordinator -> Command Parser: Frame
Coordinator --> Dispatcher: Command 
Coordinator -> ErrorHandler: Error Handling


ErrorHandler -> ResponseStreamer

Dispatcher --> Queue: enqueues Command
